spring.application.name=websocket
spring.datasource.url = jdbc:h2:mem:userDB
spring.datasource.driver-class-name=rg.h2.Driver
spring.datasource.username = sa
spring.datasource.password = root
spring.he.console.enabled = true
